# -*- coding: utf-8 -*-
"""Grupo_12_Tarea2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3CdoMLHApVW0WoCUhaU_XlAKth7GXZ8

I.
"""

!pip install pandas

import pandas as pd

data_ciudades = {
    'Ciudad' :['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Iquitos', 'Huancayo', 'Tacna', 'Pucallpa'],
    'Habitantes' :[1047996, 100169, 92331, 428450, 305717, 484475, 441649, 385098, 294395, 283734],
    'Area_km2' :[2672.28, 1545.77, 1487.7, 116.5, 279.89, 6217.26, 368.9, 109.19, 59.4, 483.44],
    'Altitud_m' :[154, 2325, 34, 3399, 29, 29, 106, 3271, 562, 156],
    'Densidad_poblacion_por_km2' :[3924, 64.8, 62.1, 3673, 1091.6, 77.9, 1196, 3528.6, 4966, 587.2]
    }

nof = pd.DataFrame (data_ciudades)
nof

"""II."""

data_ciudades_2 = {
'Ciudad': ['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Iquitos', 'Huancayo', 'Tacna', 'Pucallpa'],
'Gentilicio': ['Limense', 'Arequipeño', 'Trujillano', 'Cusqueño', 'Chiclayano', 'Piurano', 'Iquiteño', 'Huancaino', ' Tacneño', 'Pucallpino'],
'Provinvia': ['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Maynas', 'Huancayo', 'Tacna', 'Coronel Portillo'],
'Region': ['Lima', 'Arequipa', 'La Libertad', 'Cusco', 'Lambayeque', 'Piura', 'Loreto', 'Junin', 'Tacna', 'Ucayali']
}

nombres = pd.DataFrame (data_ciudades_2)
nombres

"""III."""

cuadro_1 = pd.merge(nof, nombres, on='Ciudad', how='outer')
cuadro_1

"""IV."""

import numpy as np

!pip install matplotlib

import matplotlib.pyplot as plt

cuadro_1.set_index('Ciudad', inplace=True)

cuadro_1.sort_values(by='Densidad_poblacion_por_km2', axis=0, ascending=False, inplace=True)
cuadro_1_top10 = cuadro_1['Densidad_poblacion_por_km2'].head(10)
cuadro_1_top10

cuadro_1.sort_values(by='Densidad_poblacion_por_km2', axis=0, ascending=True, inplace=True)
fig, ax = plt.subplots(figsize=(5, 5))
ax.barh(cuadro_1_top10.index, cuadro_1_top10, color='darkblue')
ax.set_xlabel('Densidad Poblacional por km2')
ax.set_title('Densidad Poblacional por km2 de las Ciudades en Perú')
plt.show()

"""Mimina densidad poblacional: 62.1 - Trujillo

Maxima densidad poblacional: 4966 - Tacna

V.
"""

fig, ax = plt.subplots(figsize=(12,6))

ax.bar(x = cuadro_1.index, height= cuadro_1['Habitantes'], color='skyblue')
ax.set_xlabel('Ciudad')
ax.set_ylabel('Habitantes')
ax.set_title('Número de Habitantes por Ciudad en Perú')
ax.tick_params(axis="x", rotation=90)
plt.show()

"""VI."""

fig, ax = plt.subplots(figsize=(10, 6))
ax.scatter(cuadro_1['Altitud_m'], cuadro_1['Habitantes'], color='green')
ax.set_title('Relación entre Altitud y Número de Habitantes de las Ciudades en Perú')
ax.set_xlabel('Habitantes')
ax.set_ylabel('Altitud (m)')
plt.show()