# -*- coding: utf-8 -*-
"""GRUPO_12_Tarea1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6kKgBaTawz2cdnRJC55XBwY_bkS9SsA
"""

x=6
if x%2==0 and x%3==0:
    print("es multiplo de 2 y 3")
elif x%2==0:
    print("es multiplo de 2")
elif x%3==0:
    print("es multiplo de 3")
else:
    print("otro caso.")

for x in range(1,101):
    if x%3==0 and x%5==0:
        print("FizzBuzz")
    elif x%3==0:
        print("Fizz")
    elif x%5==0:
        print("Buzz")
    else:
        print(x)

def calcular_descuento(total):
  if total >= 1000:
    descuento = 0.2
  elif total >= 500:
    descuento = 0.1
  else:
    descuento = 0
  total_final= total*(1-descuento)
  return total_final

calcular_descuento(1200)

calcular_descuento(750)

calcular_descuento(300)

def clasificar_edad(edad):
  if edad >= 65:
    edad="Adulto Mayor"
  elif edad >= 25:
    edad="Adulto"
  elif edad >= 18:
    edad="Joven"
  elif edad >= 12:
    edad="Adolescente"
  elif edad < 12:
    edad="Ñiño"
  return edad

clasificar_edad(10)

clasificar_edad(19)

clasificar_edad(25)

clasificar_edad(70)

def calcular_craest(media_personal,media_curso,desviacion_curso):
  '''
  Objetivo:
    -Calcular el CRAEST del curso.
  Input:
    -media personal: Nota final del curso.
    -media del curso: Promedio de notas de los alumnos del curso.
    -desviacion estandar del curso: Desviacion estandar de las notas de los alumnos del curso.
  Output:
    -CRAEST calculado
  '''
  CRAEST= (media_personal-media_curso)*10/desviacion_curso+50
  return CRAEST

calcular_craest(14,15,3.5)